#!/bin/bash
ffmpeg -re  \
      -i "https://pull-flv-l1-sg01.tiktokcdn.com/stage/stream-7249852032432016129_or4.flv" \
      -pix_fmt yuvj420p \
      -x264-params keyint=48:min-keyint=48:scenecut=-1 \
      -b:v 4500k \
      -b:a 128k \
      -ar 44100 \
      -acodec aac \
      -vcodec libx264 \
      -preset veryfast \
      -crf 28 \
      -threads 4 \
      -f flv \
      "rtmp://live-ber.twitch.tv/app/live_555128999_wrk8zt4xhB3UOmlizhZsV0jrD19Chx live=1 buffer=0"
#rtmp://a.rtmp.youtube.com/live2/ms9z-mx5s-fvjg-9tmf-93ap 1t
      #-bufsize 3968k \-framerate 30 \
      #-maxrate 1984k \
