#!/bin/bash
ffmpeg -re  \
      -i https://pull-flv-l11-sg01.tiktokcdn.com/stage/stream-7249746144580963080_or4.flv \
      -pix_fmt yuvj420p\
      -x264-params keyint=48:min-keyint=48:scenecut=-1\
      -b:v 4500k\
      -b:a 128k\
      -ar 44100\
      -acodec aac\
      -vcodec libx264\
      -preset medium\
      -crf 28\
      -threads 4\
      -f flv\
      rtmp://live-ber.twitch.tv/app/live_555128999_wrk8zt4xhB3UOmlizhZsV0jrD19Chx
